# Generated by Django 4.2.7 on 2023-11-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Faible"), ("MEDIUM", "Moyen"), ("HIGH", "Haut")],
                max_length=255,
            ),
        ),
    ]
